# Generated by Django 4.2.5 on 2023-10-12 10:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userdata",
            old_name="permission",
            new_name="permissions",
        ),
    ]
