# Generated by Django 4.2.5 on 2023-10-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_userdata_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpermission",
            name="emp_id",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
