# Generated by Django 4.2.5 on 2023-10-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_user_employee_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="fullname",
        ),
        migrations.AddField(
            model_name="userdata",
            name="fullname",
            field=models.CharField(default=True, max_length=50),
        ),
    ]
